all:
	gcc -O2 eth_reader.c tcp_server.c rc4.c key_gen.c info_list.c md5.c timer.c -lpthread -o server
	gcc -D_CLIENT_ -O2 eth_reader.c rc4.c tcp_client.c key_gen.c info_list.c md5.c timer.c -lpthread -o client

clean:
	rm client server